site_name: Kennıkk Kauli

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette: 
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/lightbulb-outline 
        name: Turn on the lights
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-purple
      accent: deep-purple
      toggle:
        icon: material/lightbulb 
        name: Turn off the lights

plugins:
  - search
  - macros
  - social:
      enabled: !ENV [CI, false]
  - redirects:
      redirect_maps:
        'lofi.md': 'http://b.link/skk'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2025 <a href="https://kkau.li"  target="_blank" rel="noopener">Kennıkk Kauli</a>

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kkiris
    - icon: fontawesome/brands/instagram
      link: https://instagr.am/kkau.li
